export const GET_ADVERTISEMENTS = "GET_ADVERTISEMENTS";
export const GET_TOP_NAVBAR = "GET_TOP_NAVBAR";
export const GET_CAROUSEL = "GET_CAROUSEL";
export const GET_PRODUCTS = "GET_PRODUCTS";

export const UPDATE_TO_CART = "UPDATE_TO_CART";