export const GET_ADVERTISEMENTS = "GET_ADVERTISEMENTS";
export const GET_TOP_NAVBAR = "GET_TOP_NAVBAR";
export const GET_CAROUSEL = "GET_CAROUSEL";
export const GET_PRODUCTS = "GET_PRODUCTS";

export const UPDATE_TO_CART = "UPDATE_TO_CART";

export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAIL = "SIGN_IN_FAIL";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";

export const CHECK_MAIL_AVAİLABLE_TRUE = "CHECK_MAIL_AVAİLABLE_TRUE";
export const CHECK_MAIL_AVAİLABLE_FALSE = "CHECK_MAIL_AVAİLABLE_FALSE";
